### ISSUE TITLE
problem normalising my data with premessa

### ISSUE THREAD

**Issue by stefk7** [ParkerICI/premessa#54] opened 2023-10-01 08:02 UTC
Hi I am getting the following error message when trying to normalise some of my data:

Some data values of 'Tb159Di' channel exceed its $PnR value 12000 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
Warning in readFCSdata(con, offsets, txt, transformation, which.lines, scale, 

Warning in readFCSdata(con, offsets, txt, transformation, which.lines, scale,  :
  Some data values of 'Time' channel exceed its $PnR value 12607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'

some data files are working well but for the ones that are not working that is the message I am getting

I am not sure what to do can anyone help?
![error message in premessa](https://github.com/ParkerICI/premessa/assets/146622289/563eb324-4e4e-449e-a8cd-5b6e75122637)

**Comment by SamGG** [comment] 2023-10-01 08:57
Hi,
I solved this in my fork https://github.com/i-cyto/premessa
If you want to try, install it
library(devtools)
install_github("i-cyto/premessa")
And let me know,
Samuel

**Comment by stefk7** [comment] 2023-10-01 10:04
Hi,

thanks for your response. When you say you solved it, was there an error with the software? I uninstalled premessa and re uploaded your fork, then I pasted the command: 

> library(premessa)
> normalizer_GUI() 

to try again to normalise my files again but I see the following message and then the GUI remains greyed out/freezes:

Warning: Error in flowCore_read.FCS: could not find function "flowCore_read.FCS"
 63: <reactive:get_fcs> [C:\Users\Chetan\AppData\Local\R\win-library\4.3\premessa\normalizer_shinyGUI/server.R#242]
 47: get_fcs
 46: observe [C:\Users\Chetan\AppData\Local\R\win-library\4.3\premessa\normalizer_shinyGUI/server.R#301]
 45: <observer>
 2: shiny::runApp
 1: normalizer_GUI
 
any ideas what is going on?

thanks again

**Comment by SamGG** [comment] 2023-10-01 10:29
The error is little weird and I just found a way to reproduce it. I look at it right now.

**Comment by stefk7** [comment] 2023-10-01 10:30
Great thank you 🙏🏽

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SamGG** [comment] 2023-10-01 11:08
I forgot that Shiny apps are considered as external users of the library. It works in my hands. Let me know.

**Comment by stefk7** [comment] 2023-10-01 11:13
Hi, not sure what you mean by shiny apps I am new to using R/premessa. I just tried again it is doing the same thing as before,  GUI remains greyed out/freezes:

Warning: Error in flowCore_read.FCS: could not find function "flowCore_read.FCS"
63: reactive:get_fcs [C:\Users\Chetan\AppData\Local\R\win-library\4.3\premessa\normalizer_shinyGUI/server.R#242]
47: get_fcs
46: observe [C:\Users\Chetan\AppData\Local\R\win-library\4.3\premessa\normalizer_shinyGUI/server.R#301]
45: 
2: shiny::runApp
1: normalizer_GUI

is there any way to make your fork work for me and fix the error “Warning: Error in flowCore_read.FCS: could not find function "flowCore_read.FCS"?? 

Thanks

**Comment by SamGG** [comment] 2023-10-01 11:56
You should unload the package from your current R session,

```
detach("package:premessa", unload = TRUE)
```
 then reinstall from github,
```
library(devtools)
install_github("i-cyto/premessa")
```
and try again.
```
library(premessa)
normalizer_GUI()
```

**Comment by stefk7** [comment] 2023-10-01 12:02
Won't let me run the first command it is saying

Error in detach("package:premessa", unload = TRUE) :  invalid 'name' argument

**Comment by SamGG** [comment] 2023-10-01 12:14
Means that the package is already removed from the current R session. Go to next step.

**Comment by stefk7** [comment] 2023-10-01 12:40
Seems to have fixed it can't thank you enough!

**Comment by stefk7** [comment] 2023-10-01 12:53
Listening on http://127.0.0.1:7308
Warning in readFCSdata(con, offsets, txt, transformation, which.lines, scale,  :
  Error in reading data stream for file '/Volumes/research-data/PRJ-2023_FBSS_SCS/CyTOF Data/20230906_FBSS_Batch1/FCS RAW FILES/workspace complete with all tubes and concatenated files/20230906_FBSS_batch1_tube2_03.d20230906-u061237.FCS'/nData may be truncated!
Warning: Error in flowCore::read.FCS: file/Volumes/research-data/PRJ-2023_FBSS_SCS/CyTOF Data/20230906_FBSS_Batch1/FCS RAW FILES/workspace complete with all tubes and concatenated files/20230906_FBSS_batch1_tube2_03.d20230906-u061237.FCSseems to be corrupted. 
 The actual number of cells in data section (2305611) is not consistent with keyword '$TOT' (2703183)
  2: shiny::runApp
  1: normalizer_GUI

Do you know what this means?

**Comment by SamGG** [comment] 2023-10-01 15:49
Is "/Volumes/research-data/PRJ-2023_FBSS_SCS/CyTOF Data/20230906_FBSS_Batch1/FCS RAW FILES/workspace complete with all tubes and concatenated files/20230906_FBSS_batch1_tube2_03.d20230906-u061237.FCS" the name of a single FCS? You should try to make it smaller, although I don't think it's the problem.
Each time I saw such an error (that is not due to Premessa), it originates from FlowJo. I think this file results from some gating in FJ. When there are a lot of files in a FJ workspace, this may occur if we don't wait enough time to let FJ update the gating strategy. In fact, FJ is updating the gating when it opens and when the user moves a gate. Redo the export of this file, and the error should disappear.
This error sounds more related to flowCore package rather than Premessa, although flowCore can only alert the user about the inconstency of cells count, which is done by raising out this error.
If your original question is answered, please close this issue, and feel free to start another one for a different subject.
Best,
Samuel

**Comment by SamGG** [comment] 2023-10-01 15:50
And congrat for your first issue in github :-)

**Comment by stefk7** [comment] 2023-10-01 23:00
It's not only the name of the FCS it's also the location of the file which is within many different folders and through a server which I'm accessing. Ok great thank you very much I will try that. Will this thread still be visible if I close it?

**Closed as completed** 2023-10-02 01:54 UTC

**Comment by SamGG** [comment] 2023-10-02 06:29
The issue is closed, ie solved, but still accessible and findable.
